NumPy = fast, powerful way to work with large amounts of numbers in Python -->Godfather of Data Science

ndarray is the main array object in numpy

Use NumPy when:

    Working with large data
    Doing math calculations
    Building ML / AI projects

NumPy can handle:

1. Math operations (add, multiply)
2. Statistics (mean, median)
3. Linear algebra (matrices)
4. Random numbers
5. Sorting & filtering
6. Fourier transforms (advanced)

CREATING NUMPY ARRAYS

In [1]:
import numpy as np

#np.array
a=np.array([1,2,3])
print(a)


[1 2 3]


In [5]:
#2D Array and 3D Array
b=np.array([[4,5,6],[7,8,9],[10,11,12]])
print("2D Array\n",b)

c=np.array([[[10,20,30],[40,50,60],[70,80,90]],[[100,110,120],[130,140,150],[160,170,180]],[[190,200,210],[220,230,240],[250,260,270]]])
print("3D Array\n",c)


2D Array
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3D Array
 [[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[190 200 210]
  [220 230 240]
  [250 260 270]]]


In [7]:
# dtype -- Creating Arrays with specific datatype
d=np.array([1,2,3],dtype="float")
print(d)

[1. 2. 3.]


In [8]:
#np.arange
npa=np.arange(1,10,2)
print(npa)

[1 3 5 7 9]


In [10]:
#np.reshape
npr=np.arange(1,13).reshape(4,3)
print(npr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
#np.ones(shape, dtype=None, order='C', *, device=None, like=None) and np.zeroes(shape, dtype=None, order='C', *, device=None, like=None)
npo=np.ones((2,3),dtype=int)
print("npo\n",npo)

npz=np.zeros((4,6),dtype=int)
print("npz\n",npz)

npo
 [[1 1 1]
 [1 1 1]]
npz
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
#np.random.random
npr=np.random.random((1,10))
print(npr)

[[0.58145794 0.62131855 0.50380104 0.30741369 0.72360129 0.19734698
  0.43408291 0.12796975 0.88905804 0.25974986]]


In [23]:
#np.linspace -- returns points in equal distance
npl=np.linspace(-20,20,4,dtype=int)
print(npl)


[-20  -7   6  20]


In [26]:
#np.identity -- returns an identity matrix with n rows
npi=np.identity(4,dtype=int)
print(npi)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


ARRAY ATTRIBUTES

In [29]:
a=np.arange(10)
b=np.arange(12,dtype=float).reshape(2,6)
c=np.arange(8).reshape(2,2,2)

In [30]:
#ndim
print(a.ndim,b.ndim,c.ndim)

1 2 3


In [31]:
#shape
print(a.shape,b.shape,c.shape)

(10,) (2, 6) (2, 2, 2)


In [32]:
#size -- no of elements
print(a.size,b.size,c.size)

10 12 8


In [36]:
#itemsize -- size of each item in ndarray 
#dtype -- datatype of ndarray

print(a.itemsize)
print(a.dtype,b.dtype,c.dtype)

8
int64 float64 int64


In [42]:
#astype
c=c.astype(np.int32)

print(c,c.dtype)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] int32


ARRAY OPERATIONS

In [43]:
a1=np.arange(10,20).reshape(2,5)
a2=np.arange(20,30).reshape(5,2)

In [46]:
print(a1 ,"\n\n", a2)

[[10 11 12 13 14]
 [15 16 17 18 19]] 

 [[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


In [49]:
#Scalar Operations

#Arithmetic

print(a1+2)
print(a1-3)
print(a2*3)
print(a2//9)
print(a1%2)
print(a2**2)

[[12 13 14 15 16]
 [17 18 19 20 21]]
[[ 7  8  9 10 11]
 [12 13 14 15 16]]
[[60 63]
 [66 69]
 [72 75]
 [78 81]
 [84 87]]
[[2 2]
 [2 2]
 [2 2]
 [2 3]
 [3 3]]
[[0 1 0 1 0]
 [1 0 1 0 1]]
[[400 441]
 [484 529]
 [576 625]
 [676 729]
 [784 841]]


In [52]:
#Relational

print(a2>5,"\n\n")
print(a1<=20)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]] 


[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [54]:
a3=np.arange(10,22).reshape((3,4))
a4=np.arange(22,34).reshape((3,4))

In [56]:
#Vector Operations -- Operations on two numpy arrays
print(a3+a4)
print(a3-a4)
print(a3*a4)
print(a3/a4)
print(a3%a4)
print(a3**a4)

[[32 34 36 38]
 [40 42 44 46]
 [48 50 52 54]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[220 253 288 325]
 [364 405 448 493]
 [540 589 640 693]]
[[0.45454545 0.47826087 0.5        0.52      ]
 [0.53846154 0.55555556 0.57142857 0.5862069 ]
 [0.6        0.61290323 0.625      0.63636364]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ 1864712049423024128  6839173302027254275 -5124814900970913792
   7440561802173124845]
 [ 6505943899796668416  4664996673054274223                    0
  -2937492190078896175]
 [-6577369351890927616  2421078562627535771                    0
   1402373082338981781]]


ARRAY FUNCTIONS

In [72]:
#np.round(a, decimals=0, out=None)
a1=np.random.random((3,3))
a1=np.round(a1*100,4)
a1

[[0.75126085 0.00836328 0.18486809]
 [0.2193864  0.02589112 0.58473958]
 [0.66073597 0.36590621 0.77142892]]


array([[75.1261,  0.8363, 18.4868],
       [21.9386,  2.5891, 58.474 ],
       [66.0736, 36.5906, 77.1429]])

In [80]:
#max/min/sum/prod
#column - 0 and row - 1 for axis
print(np.max(a1,axis=1))

[75.1261 58.474  77.1429]


In [81]:
#mean/median/std/var
print(np.mean(a1,axis=0))
print(np.median(a1,axis=1))
print(np.std(a1,axis=0))
print(np.var(a1,axis=1))



[54.37943333 13.33866667 51.3679    ]
[18.4868 21.9386 66.0736]
[23.23492615 16.45716419 24.46776123]
[1004.28053764  536.92896127  292.91841409]


In [83]:
#trigonometric functions
print(np.sin(a1))

[[-0.26877758  0.74216842 -0.35485215]
 [ 0.05252439  0.52481065  0.9378077 ]
 [-0.09998692 -0.89503597  0.98492092]]


In [84]:
#dot product
a1=np.arange(10,22).reshape((3,4))
a2=np.arange(22,34).reshape((4,3))
a2

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [85]:
#dot product
print(np.dot(a2,a3))

[[ 974 1043 1112 1181]
 [1100 1178 1256 1334]
 [1226 1313 1400 1487]
 [1352 1448 1544 1640]]


In [89]:
# log and exponents
print(np.log(a1),"\n\n")
print(np.exp(a1))

[[2.30258509 2.39789527 2.48490665 2.56494936]
 [2.63905733 2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227 3.04452244]] 


[[2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05]
 [1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08 1.31881573e+09]]


In [96]:
# round , floor and ceil
npr=np.random.random((2,3,4))*100
npro=np.round(npr)
nprf=np.floor(npr)
nprc=np.ceil(npr)

print(f"npro - {npro}\n\n nprf - {nprf}\n\n nprc - {nprc}\n")

npro - [[[67. 13. 37. 28.]
  [60. 34. 44. 25.]
  [77. 75. 65. 95.]]

 [[22.  9. 99. 54.]
  [72. 43.  0.  2.]
  [79.  4. 67. 34.]]]

 nprf - [[[67. 12. 37. 28.]
  [59. 33. 43. 24.]
  [77. 75. 64. 94.]]

 [[21.  9. 98. 54.]
  [72. 42.  0.  1.]
  [79.  4. 67. 33.]]]

 nprc - [[[68. 13. 38. 29.]
  [60. 34. 44. 25.]
  [78. 76. 65. 95.]]

 [[22. 10. 99. 55.]
  [73. 43.  1.  2.]
  [80.  5. 68. 34.]]]



INDEXING AND SLICING

In [ ]:
a2=np.arange(12,24).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [102]:
#indexing
print(a3[2,1,2])
print(a3[1,0,1])
print(a3[1,1,0])

23
10
12


In [115]:
# slicing
print(a2,"\n\n")
print(a2[::2,0::2])
print(a2,"\n\n")
print(a3)
print("\n\n")
print(a3[0:,1:,0:])


[[22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]] 


[[22 24]
 [28 30]]
[[22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]] 


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


SLICING PRACTISE

In [116]:
# slicing practice
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(a3[2:,1:,1:]) #print [22 23 25 26]
print(a3[1,0:,1]) #print [10 13 16]
print(a3[0::2,0,0::2])#print [0 2 18 20]

[[[22 23]
  [25 26]]]
[10 13 16]
[[ 0  2]
 [18 20]]


ITERATION

In [129]:
for i in np.nditer(a3):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

RESHAPING

In [131]:
#np.reshape()
npr=np.arange(10,22).reshape((3,4))
print(npr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [133]:
#np.transpose
npt=np.arange(10,22).reshape((6,2))
print(npt,"\n\n")
print(np.transpose(npt))

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]] 


[[10 12 14 16 18 20]
 [11 13 15 17 19 21]]


In [134]:
#np.ravel -- flattens a numpy array to 1-d array
npr=np.ravel(npt)
print(npr)

[10 11 12 13 14 15 16 17 18 19 20 21]


STACKING NUMPY ARRAYS

In [136]:
a1=np.arange(10,26).reshape((4,4))
a2=np.arange(20,36).reshape((4,4))
a2

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [139]:
#Horizontal Stacking -- only applicable to ndarrays of same shape
#Vertical Stacking -- only applicable to ndarrays of same shape

print(np.hstack((a1,a2)))
print("\n\n")
np.vstack((a1,a2))


[[10 11 12 13 20 21 22 23]
 [14 15 16 17 24 25 26 27]
 [18 19 20 21 28 29 30 31]
 [22 23 24 25 32 33 34 35]]





array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])